swagger: "2.0"
################################################################################
#                              API Information                                 #
################################################################################
info:
  description: 汽车站_后台模块_接口文档
  version: 0.0.1
  title: 汽车站后台模块接口文档
host: localhost:8081
schemes:
- http
- https
basePath: /
consumes:
- application/json
produces:
- application/json
paths:
################################################################################
#                                  系统模块                                    #
################################################################################
  /admin/busstation/register:
    post:
      operationId: register
      tags:
      - '[后台]用户注册'
      summary: 用户注册
      parameters:
      - name: register_input
        in: body
        description: 注册信息，登录名，密码
        schema:
          $ref: '#/definitions/register_input'
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/common_response'
  /admin/busstation/login:
    post:
      operationId: login
      tags: 
      - '[后台]用户登陆'
      summary: 用户登陆
      parameters:
      - name: login_input
        in: body
        description: 登陆信息，登录名，密码
        schema:
          $ref: '#/definitions/login_input'
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/common_response'
  /admin/busstation/reset:
    post:
      operationId: reset
      tags: 
      - '[后台]用户重置密码'
      summary: 用户重置密码
      parameters:
      - name: reset_input
        in: body
        description: 重置密码信息，登录名，旧密码，新密码
        schema:
          $ref: '#/definitions/reset_input'
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/common_response'
  /admin/busstation/logout:
    get:
      operationId: logout
      tags: 
      - '[后台]用户退出'
      summary: 用户退出
      parameters:
      - name: user_name
        type: string
        description: 用户名
        in: path
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/common_response'
  /admin/busstation/get_my_info:
    get:
      operationId: get_my_info
      tags:
      - '[后台]获取个人信息'
      summary: 获取个人信息
      parameters:
      - name: user_name
        in: paths
        required: true
        description: 当前用户名
        type: string
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/get_my_info_response'
  /admin/busstation/update_my_info:
    post:
      operationId: update_my_info
      tags:
      - '[后台]更新个人信息'
      summary: 更新个人信息
      parameters:
      - name: update_my_info_input
        in: body
        required: true
        description: 更新个人信息输入
        schema:
          $ref: '#/definitions/update_my_info_input'
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/common_response'

################################################################################
#                                   用户模块                                   #
################################################################################
  /admin/busstation/user:
    post:
      operationId: get_user
      tags:
      - '[后台]获取用户'
      summary: 获取用户
      parameters:
      - name: id
        in: query
        required: false
        type: integer
        description: 用户id（数据库主键）
      - name: user_name
        in: query
        required: false
        type: string
        description: 用户名（登录名）
      - name: name
        in: query
        required: false
        type: string
        description: 真实名字
      - name: sex
        in: query
        required: false
        type: integer
        description: 性别，1:男，2:女，0:未知
      - name: phone
        in: query
        required: false
        type: string
        description: 用户手机号
      - name: type
        in: query
        required: false
        type: integer
        description: 权限：1:管理员，2:普通用户
      - name: status
        in: query
        required: false
        type: integer
        description: 状态：1:启用，2:禁用（注册完默认是2禁用）
      - name: limit
        in: query
        required: false
        description: 每页数量
        type: integer
      - name: offset
        in: query
        required: false
        type: integer
        description: 偏移量
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/get_user_response'
  /admin/busstation/updateUser:
    post:
      operationId: update_user
      tags:
      - '[后台]更新用户信息'
      summary: 更新用户信息
      parameters:
      - name: update_user_input
        in: body
        required: true
        description: 更新个人信息输入
        schema:
          $ref: '#/definitions/update_user_input'
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/common_response'
################################################################################
#                              车站模块                                         #
################################################################################   
  /admin/busstation/station:
    post:
      operationId: get_station
      tags:
      - '[后台]获取车站信息'
      summary: 获取车站信息
      parameters:
      - name: id
        in: query
        required: false
        type: integer
        description: 车站id（数据库主键）
      - name: name
        in: query
        required: false
        type: string
        description: 车站名
      - name: province_code
        in: query
        required: false
        type: integer
        description: 省编号
      - name: province
        in: query
        required: false
        type: string
        description: 省名
      - name: city_code
        in: query
        required: false
        type: integer
        description: 市编号
      - name: city
        in: query
        required: false
        type: string
        description: 市名
      - name: section_code
        in: query
        required: false
        type: integer
        description: 区编号
      - name: section
        in: query
        description: 区名
        type: string
      - name: status
        in: query
        required: false
        type: integer
        description: 状态，1-启用，2-禁用
      - name: limit
        in: query
        description: 每页数量
        type: integer
        required: false
      - name: offset
        in: query
        required: false
        type: integer
        description: 偏移量
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/get_station_response'
  /admin/busstation/save_station:
    post:
      operationId: save_station
      tags:
      - '[后台]保存车站信息'
      summary: 保存车站信息
      parameters:
      - name: id
        in: query
        required: false
        type: integer
        description: 车站id（数据库主键）
      - name: name
        in: query
        required: false
        type: string
        description: 车站名
      - name: province_code
        in: query
        required: false
        type: integer
        description: 省编号
      - name: province
        in: query
        required: false
        type: string
        description: 省名
      - name: city_code
        in: query
        required: false
        type: integer
        description: 市编号
      - name: city
        in: query
        required: false
        type: string
        description: 市名
      - name: section_code
        in: query
        required: false
        type: integer
        description: 区编号
      - name: section
        in: query
        description: 区名
        type: string
      - name: address
        in: query
        description: 详细地址
        register: false
        type: string
      - name: status
        in: query
        required: false
        type: integer
        description: 状态，1-启用，2-禁用
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/common_response'
################################################################################
#                              车次模块                                         #
################################################################################ 
  /admin/busstation/list:
    post:
      operationId: get_list
      tags:
      - '[后台]获取车站信息'
      summary: 获取车站信息
      parameters:
      - name: id
        in: query
        required: false
        type: integer
        description: 车次id（数据库主键）
      - name: first_station_name
        in: query
        required: false
        type: string 
        description: 始发站车站名
      - name: last_station_name
        in: query
        required: false
        type: string 
        description: 终点站车站名
      - name: via
        in: query
        required: false
        type: string 
        description: 途经站名
      - name: status
        in: query
        required: false
        type: integer
        description: 状态，1-启用，2-禁用
      - name: limit
        in: query
        description: 每页数量
        type: integer
        required: false
      - name: offset
        in: query
        required: false
        type: integer
        description: 偏移量
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/get_list_response'
  /admin/busstation/save_list:
    post:
      operationId: save_list
      tags:
      - '[后台]保存车次信息'
      summary: 保存车次信息
      parameters:
      - name: id
        in: query
        required: false
        type: integer
        description: 车次id（数据库主键）
      - name: first_station
        required: true
        description: 始发站id
      - name: first_station_name
        in: query
        required: false
        type: string 
        description: 始发站车站名
      - name: leave_time
        in: query
        description: 出发时间
        type: integer
        format: int64
        required: true
      - name: last_station
        in: query
        description: 终点站id
        type: integer
        required: true
      - name: last_station_name
        in: query
        required: false
        type: string 
        description: 终点站车站名
      - name: arrive_time
        required: true
        type: integer
        format: int64
        in: query
      - name: via
        in: query
        required: false
        type: string 
        description: 途经站名
      - name: seat
        in: query
        description: 座位数
        type: integer
        required: true
      - name: price
        in: query
        description: 价钱
        type: string
        required: true
      - name: distance
        in: query
        description: 距离
        type: integer
        required: true
      - name: status
        in: query
        required: false
        type: integer
        description: 状态，1-启用，2-禁用
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/common_response'
################################################################################
#                         通用response                                         #
################################################################################
definitions:
  common_response:
    description: 通用应答结构
    type: object
    properties:
      code:
        type: integer
        description: 响应码，0为成功，1为失败
      success:
        type: boolean
        description: 是否成功
################################################################################
#                             系统模块                                         #
################################################################################
  register_input:
    type: object
    properties:
      user_name:
        type: string
        description: 用户名
      password:
        type: string
        description: 密码
  login_input:
    type: object
    properties:
      user_name:
        type: string
        description: 用户名
      password:
        type: string
        description: 密码
  reset_input:
    type: object
    properties:
      user_name:
        type: string
        description: 用户名
      old_password:
        type: string
        description: 旧密码
      new_password: 
        type: string
        description: 新密码
  get_my_info_response:
    type: object
    properties:
      id:
        type: integer
        description: 个人id
      user_name:
        type: string
        description: 用户名
      name: 
        type: string
        description: 真是姓名
      id_card: 
        type: string
        description: 身份证号码
      sex: 
        type: integer
        description: 性别，1-男，2-女，0-未知
      phone: 
        type: string
        description: 手机号码
      email: 
        type: string
        description: 邮箱
      type: 
        type: integer
        description: 权限，1-管理员，2-普通用户
      status:
        type: integer
        description: 状态，1-启用，2-禁用（普通用户注册完默认是启用，管理员注册完默认是2禁用）
      create_time: 
        type: integer
        format: int64
        description: 注册时间
  update_my_info_input:
    type: object
    properties:
      id:
        type: integer
        description: 个人id
      name: 
        type: string
        description: 真是姓名
      id_card: 
        type: string
        description: 身份证号码
      sex: 
        type: integer
        description: 性别，1-男，2-女，0-未知
      phone: 
        type: string
        description: 手机号码
      email: 
        type: string
        description: 邮箱
################################################################################
#                                所有用户信息                                  #
################################################################################
  # 后台user模块
  get_user_response:
    allOf:
    - $ref: '#/definitions/common_response'
    - type: object
      properties:
        result:
          type: object
          properties:
            total:
              type: integer
            items:
              type: array
              items:
                $ref: '#/definitions/user_detail'
  user_detail:
    type: object
    properties:
      id: 
        type: integer
        description: 用户id（数据库主键）
      user_name:
        type: string
        description: 用户名
      name: 
        type: string
        description: 真是姓名
      id_card: 
        type: string
        description: 身份证号码
      sex: 
        type: integer
        desc: 性别：1男，2女，0未知
      phone:
        type: string
        description: 手机号码
      email: 
        type: string
        description: 邮箱
      type:
        type: integer
        description: 权限，1:管理员，2:普通用户
      status: 
        type: integer
        description: 状态，1:启用，2:禁用（普通用户注册完默认是1启用，管理员注册完默认是2禁用）
      create_time: 
        type: string
        description: 创建时间（注册时间）
  update_user_input:
    type: object
    properties:
      id: 
        type: integer
        description: 用户id
      name: 
        type: string
        description: 真实名字
      id_card: 
        type: string
        description: 身份证号
      sex: 
        type: string
        description: 性别，1-男，2-女，0-未知
      phone: 
        type: string
        description: 手机号码
      email:
        type: string
        description: 邮箱
      status:
        type: integer
        description: 状态，1-启用，2-禁用（普通用户注册完默认是启用，管理员注册完默认是2禁用）
################################################################################
#                                    车站编辑                                   #
################################################################################
  get_station_response:
    allOf:
    - $ref: '#/definitions/common_response'
    - type: object
      properties:
        result:
          type: object
          properties:
            total:
              type: integer
            items:
              type: array
              items:
                $ref: '#/definitions/station_detail'
  station_detail:
    type: object
    properties:
      id:
        type: integer
        description: 车站id（数据库主键）
      name:
        type: string
        description: 车站名
      province_code:
        type: integer
        description: 省编号
      province:
        type: string
        description: 省名
      city_code:
        type: integer
        description: 市编号
      city:
        type: string
        description: 市名
      section_code:
        type: integer
        description: 区编号
      section:
        type: string
        description: 区名
      address:
        type: string
        description: 详细地址
      status:
        type: integer
        description: 状态，1-启用，2-禁用
      create_time:
        type: string
        description: 创建时间
################################################################################
#                                    车站编辑                                   #
################################################################################
  get_list_response:
    allOf:
    - $ref: '#/definitions/common_response'
    - type: object
      properties:
        result:
          type: object
          properties:
            total:
              type: integer
            items:
              type: array
              items:
                $ref: '#/definitions/list_detail'
  list_detail:
    type: object
    properties:
      id:
        type: integer
        description: 车次id（数据库主键）
      first_station:
        type: integer
        description: 始发站id
      first_station_name:
        type: string
        description: 始发站名
      leave_time:
        type: integer
        format: int64
        description: 出发时间
      last_station:
        type: integer
        description: 终点站id
      last_station_name:
        type: string
        description: 终点站名
      arrive_time:
        type: integer
        format: int64
        description: 到站时间
      via:
        type: string
        description: 途经站
      seat:
        type: integer
        description: 座位数
      price:
        type: string
        description: 价钱
      distance:
        type: integer
        description: 距离
      status:
        type: integer
        description: 状态，1-启用，2-禁用
      create_time: 
        type: integer
        format: int64
        description: 创建时间



      