spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-5v933qgx.gz.tencentcdb.com:10076/BusStation?characterEncoding=utf8
    username: root
    password: root1234_
    type: com.mchange.v2.c3p0.ComboPooledDataSource